[
project
]
name = "npgrad"
version = "0.1"
description = ""  # You might want to add a description
authors = []  # You might want to add author information
dependencies = [
    "numpy>=2.0.0",
]
requires-python = ">=3.9"

[
build-system
]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[
tool.setuptools
]
packages = ["npgrad"]  # Assumes your package is named "npgrad"